version: "3"
services:
    node:
        container_name: node
        user: "${UID}:${GID}"
        build: .
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - /home:/home
            - ./app:/app
        tty: true
        ports:
            - 3000:3000
